### ISSUE TITLE
Support for Animation Between Steps

### ISSUE THREAD

**Issue by indivisable** [24ark/react-native-step-indicator#1]
![jan-31-2017 23-30-50](https://cloud.githubusercontent.com/assets/22860891/22496191/64007fac-e80d-11e6-82d0-258b98cfe968.gif)

Was curious if there was support for animation between steps? I have some code that may achieve this. I'll test the library tomm and see if I can integrate.

Great library been looking for a nice solution for this one for a while :)

**Update:** I have attached this zip with working animation version built on top of 'react-native-scrollable-tab-view' - I have not yet reviewed your solution but this might be a nice feature to support this as well.

[Archive.zip](https://github.com/24ark/react-native-step-indicator/files/743928/Archive.zip)

**Comment by 24ark** [comment]
@indivisable I have added support for animation between steps in v0.0.2.

Thanks

**Comment by indivisable** [comment]
@24ark Is there an example of how to use this or is it inherit? I updated library to 0.0.5 and do not see any animations, any ideas?
