### ISSUE TITLE
labelAlign TypeError Typescript

### ISSUE THREAD

**Issue by ArthurPedroti** [24ark/react-native-step-indicator#105]
Hello guys,

Whenever I put the param 'labelAlign' on the customStyles I got the a type error indicating the types don't match. If I take off, the error go away.

![image](https://user-images.githubusercontent.com/52859409/93779937-e7a6fe00-fbfd-11ea-98a8-d59404b052e9.png)

**Comment by FeMaffezzolli** [comment]
@ArthurPedroti , have you been able to find a solution?

**Comment by hgopi** [comment]
I fixed it by applying the `labelAlign` as below:

`labelAlign: "flex-start" as 'flex-start',`
