### ISSUE TITLE
Step movement onPress()

### ISSUE THREAD

**Issue by Thanmai-C** [24ark/react-native-step-indicator#11]
Hi,
I have written the same code from your example (HorizontalStepIndicator.js).
Happy with it,but i wanted something like i have a button below to the step indicators, and when i click on that button the step has to move to the next,so how do i achieve that. 
(what is the onPress() that i have to write on that button)?
Please help.

**Comment by valeriaabo** [comment]
I need this too! Any ideas?

**Comment by veb** [comment]
If you have a read through the examples you can do something like:

`<Button onPress={(page) => {this.setState({currentPage:3})}}>`

**Comment by rhenanteix** [comment]
I'm in trouble, I created a TouchableOpacity, and I'm not able to go to another step

**Comment by Shihaburabbi** [comment]
> If you have a read through the examples you can do something like:
> 
> `<Button onPress={(page) => {this.setState({currentPage:3})}}>`

try this link but not working
