### ISSUE TITLE
Not swiping when changing Page Index on Android

### ISSUE THREAD

**Issue by Mgxcx** [24ark/react-native-step-indicator#116]
Hi ! 

I used the Horizontal Step Indicator Example. 
And I added a little functionality : I passed nextPage props to my step screens, and I called this props on a button click in each step screen in order to change the currentPage state index and swipe to the next page:
![Capture d’écran 2021-04-30 à 18 21 40](https://user-images.githubusercontent.com/72705823/116725742-a7ed9380-a9e2-11eb-8197-ed20d4fe8ec9.png)

It works well on iOS but not on Android, and I don't understand where the issue is... 

You can see my code below : 
![Capture d’écran 2021-04-30 à 18 21 20](https://user-images.githubusercontent.com/72705823/116725732-a1f7b280-a9e2-11eb-8eed-938c8a3b7796.png)
![Capture d’écran 2021-04-30 à 18 20 55](https://user-images.githubusercontent.com/72705823/116725737-a4f2a300-a9e2-11eb-8ddc-6c04f4c1493f.png)

Thanks for your help 🙏

**Comment by hayder-grability** [comment]
Some notice from this theme?

**Comment by hayder-grability** [comment]
Maybe this can help you
1. create a ref
`const swiperRef = useRef<any>(null);`

2. Use the component without index
` <Swiper
          ref={swiperRef}
          loop={false}
          // index={step}
          autoplay={false}
          showsButtons={false}
          scrollEnabled={false}
          showsPagination={false}
        />`
        
 3. Then use it when use onPress 
 
`swiperRef.current.scrollTo(position);`

**Comment by Mgxcx** [comment]
It works ! Thanks a lot 🙏
