### ISSUE TITLE
Updated usage with FlatList.

### ISSUE THREAD

**Issue by jeffreymendez1993** [24ark/react-native-step-indicator#13]
Great work on the implementation. Only thing it only works with ListViews on iOS and not android.
If you convert to FlatList and add.

  renderPage = ({item}) => {
    return (
      <View style={styles.rowItem}>
        <Text style={styles.title}>{item.title}</Text>
        <Text style={styles.body}>{item.body}</Text>
      </View>
    );
  }

  getVisibleRows = (visibleRows) => {
    const visibleRowNumbers = visibleRows.viewableItems.map((row) => {
      return row.index;
    });
    this.setState({currentPage:visibleRowNumbers[0]})
  }

it will work across both platforms.

**Comment by 24ark** [comment]
@jeffreymendez1993 I have updated the example to use FlatList instead of ListView. This should now work on android too.
