### ISSUE TITLE
stepIndicatorLabelUnFinishedColor and stepIndicatorLabelFinishedColor not working 

### ISSUE THREAD

**Issue by salilbajaj** [24ark/react-native-step-indicator#17]
Here is my code

`const customStyles = {
  stepIndicatorSize: 30,
  currentStepIndicatorSize:35,
  separatorStrokeWidth: 8,
  currentStepStrokeWidth: 1,
  stepStrokeCurrentColor: '#fe7013',
  stepStrokeWidth: 3,
  stepStrokeFinishedColor: '#fe7013',
  stepStrokeUnFinishedColor: '#aaaaaa',
  separatorFinishedColor: '#fe7013',
  separatorUnFinishedColor: '#aaaaaa',
  stepIndicatorFinishedColor: 'red',
  stepIndicatorUnFinishedColor: '#ffffff',
  stepIndicatorCurrentColor: 'red',
  stepIndicatorLabelFontSize: 16,
  currentStepIndicatorLabelFontSize: 16,
  stepIndicatorLabelCurrentColor: '#fff', 
  stepIndicatorLabelFinishedColor:'#fff',
  stepIndicatorLabelUnFinishedColor: '#000',
}

 render() {
    
    return (
      <View style={styles.container}>
       <StepIndicator
         customStyles={customStyles}
         currentPosition={this.state.currentPosition}
         stepCount={3}
        
    />
      </View>
    );
  }`

stepIndicatorLabelCurrentColor is working as shown in screenshot(white) but stepIndicatorLabelFinishedColor and stepIndicatorLabelUnFinishedColor are not working

![screen shot 2017-08-27 at 5 41 50 pm](https://user-images.githubusercontent.com/14991148/29749678-2ec99054-8b4f-11e7-9ff2-d0a78dc3abd9.png)

**Comment by salilbajaj** [comment]
Basically the numbers 1 & 3 are not visible

**Comment by 24ark** [comment]
@salilbajaj  I have removed removeClippedSubviews in the latest version(0.0.8). The steps should be rendered as expected in this version.
