### ISSUE TITLE
only first indicator number rendered

### ISSUE THREAD

**Issue by readthecodes** [24ark/react-native-step-indicator#23]
only first indicator number rendered by default，RN version 4.8.3，iOS emulator
<img width="383" alt="indicator_disappear 2x" src="https://user-images.githubusercontent.com/9927974/31348178-5e7f8838-ace4-11e7-8637-3d86d5e931fc.png">

**Comment by readthecodes** [comment]
it works by remove the 'removeClippedSubviews' prop in renderStep function

**Comment by jamesreilly5** [comment]
This happened to me too, I was able to resolve it by doing what _readthecodes_ mentioned. It's weird though because I remember this working at one stage and I don't think I bumped the version.

**Comment by 24ark** [comment]
@readthecodes @jamesreilly5 I have removed `removeClippedSubviews` in the latest version(0.0.8). The steps should be rendered as expected in this version.
