### ISSUE TITLE
[feature] Allow for custom component when rendering a step

### ISSUE THREAD

**Issue by tsvetann** [24ark/react-native-step-indicator#29]
As the title says it would be cool to allow the developer to pass custom component to be used when rendering a particular step.

**Comment by Pradeet** [comment]
working on it...

**Comment by ikhsanalatsary** [comment]
I already finished on this and use it in my own project. I will pull request for this feature.

**Comment by 24ark** [comment]
@tsvetann @ikhsanalatsary  I have added `renderStepIndicator` to the props. You can use this prop to render custom content inside step.

**Comment by ikhsanalatsary** [comment]
Thanks 👍

**Comment by rf1804** [comment]
Any example or some code snippet for how to use `renderStepIndicator` as i want to render a image of tick on finished ones. @24ark @ikhsanalatsary
