### ISSUE TITLE
onPress doesn't react to touches unless I inspect it with react-devtools

### ISSUE THREAD

**Issue by iradkot** [24ark/react-native-step-indicator#30]
I've implemented the step indicator in my app and It worked great so far, recently the onPress function of the step indicator stoped working. I dont know why, but when I inspect it (toggle inspector) and checkt it with react-devtools after I close the inspector it works again. I tried both on android studio emulator and on my android phone.
this is the code for the indicator: 
```
<StepIndicator
                        onPress={(number) => this.stepPress(number)}
                        stepCount={4}
                        customStyles={customStyles}
                        currentPosition={this.state.currentPage}
                        labels={labels}
                    />
```
and the handler:
`stepPress(number) {
        console.log(number);
        if (number <= this.state.allowPages) {
            this.setState({currentPage: number});
            this.refs.scrollview.setPage(number);
        }
        else {
            Alert.alert('you have to fill all forms before moving forward');
        }
    }`

the problem is that it doesn't even console until I open the inspector. please help thank you

**Comment by iradkot** [comment]
No idea how it happened, solved it by adding a view before it with some vertical margin..

**Comment by mayur-bhandari** [comment]
Can you provide code sample of it. I am getting the same issue. Thank You.!
