### ISSUE TITLE
Custom styles won't update

### ISSUE THREAD

**Issue by timolins** [24ark/react-native-step-indicator#31]
It's not possible to update styles after the component has been constructed. This is could be solved by storing the customStyles inside the component's state. This way it should respond to style changes.

**Comment by PriyankaAshu** [comment]
Can I know is it possible now to update customStyles dynamically ?
I Have set my styles in state and using the same in customStyles prop in StepIndicator.
                        
                                return  <StepIndicator
                                   customStyles={this.state.ongoingCustomProps}
                                   currentPosition={3}
                                   labels={labels}
                                   stepCount = {5}
                              />

But the colors are not reflecting/changing. but stepCount, currentPosition and labels are changing.

**Comment by timolins** [comment]
Yes, I submitted a pull request which adds support for dynamic styling!
Sadly it hasn't been merged yet, but you can install it directly.

https://github.com/24ark/react-native-step-indicator/pull/32
