### ISSUE TITLE
Please update example for horizontal view

### ISSUE THREAD

**Issue by ikhsanalatsary** [24ark/react-native-step-indicator#33]
![screen shot 2018-02-09 at 4 35 37 pm](https://user-images.githubusercontent.com/5897415/36021094-5788102a-0db7-11e8-9866-a2b68ca8307f.png)
Due `react-native-viewpager` is no more maintenance. So please provide an example of another package. I suggest using https://github.com/zbtang/React-Native-ViewPager

**Comment by 24ark** [comment]
@ikhsanalatsary I have updated the example to support latest react native versions. I am now using https://github.com/zbtang/React-Native-ViewPager

**Comment by ikhsanalatsary** [comment]
Thanks 👍
