### ISSUE TITLE
Compatibility issue with react-native 0.52.0

### ISSUE THREAD

**Issue by Lasith-Niro** [24ark/react-native-step-indicator#34]
I tried `react-native-step-indicator` with react-native new version. But it not worked. This is the package.json file.
{
  "name": "app-test",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "jest-expo": "25.0.0",
    "react-native-scripts": "1.11.1",
    "react-test-renderer": "16.2.0"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^25.0.0",
    "firebase": "^4.9.0",
    "react": "16.2.0",
    "react-dom": "^16.2.0",
    "react-native": "0.52.0",
    "react-native-android-kit": "^1.2.1",
    "react-native-gesture-handler": "^1.0.0-alpha.40",
    "react-native-indicators": "^0.11.1",
    "react-native-paged-scroll-view": "^2.0.4",
    "react-native-pathjs-charts": "0.0.33",
    "react-native-router-flux": "^4.0.0-beta.28",
    "react-native-step-indicator": "0.0.7",
    "react-native-tab-view": "^0.0.74",
    "react-native-tabs": "^1.0.9",
    "react-native-viewpager": "^0.2.13",
    "react-navigation": "^1.0.0-beta.27",
    "victory": "^0.25.4",
    "victory-native": "^0.17.0"
  }
}

**Comment by 24ark** [comment]
@Lasith-Niro The latest version 0.0.8 supports react native 0.54.
