### ISSUE TITLE
renderStepIndicator not working

### ISSUE THREAD

**Issue by rf1804** [24ark/react-native-step-indicator#38]
Kindly add some example in doc or example app
I want to show like this
![screen shot 2018-05-24 at 6 15 44 pm](https://user-images.githubusercontent.com/35443934/40486352-aa5a9606-5f7e-11e8-8a65-78c29ce3022c.png)
Basically i want to render tick image inside step circle and i've tried doing like this, but no success

```
<StepIndicator
           customStyles={customStyles}
           currentPosition={this.state.currentPosition}
           stepCount={3}
           renderStepIndicator={(state)=>{_this.putTickIndicator(state)}}
/>
```
```
putTickIndicator = (state)=> {
    console.log(state)
    return <Image source={require('./../../images/ic_backwd.png')} style={{tintColor: '#000000',height: 10, width:10}}/>
  }
```

**Comment by 24ark** [comment]
@rf1804 You might be missing a `return` statement here in `renderStepIndicator`.

`<StepIndicator
           customStyles={customStyles}
           currentPosition={this.state.currentPosition}
           stepCount={3}
           renderStepIndicator={(state)=>{return _this.putTickIndicator(state)}}
/>`

**Comment by rahiljain09** [comment]
![screen shot 2019-03-07 at 4 30 01 pm](https://user-images.githubusercontent.com/32325985/53952261-52fdad80-40f6-11e9-8a7b-7df66430460d.png)

I want to render Custom Image for finished and numbers for current and not finished. Tried above but everywhere image is coming even for finished.
