### ISSUE TITLE
customStyles are not updating dynamically..

### ISSUE THREAD

**Issue by PriyankaAshu** [24ark/react-native-step-indicator#42]
Can I know is it possible now to update customStyles dynamically ?
I Have set my styles in state and using the same in customStyles prop in StepIndicator.

I my case customStyle will change as pr the status change on indicator. 
                         
   return  <StepIndicator
                               customStyles={this.state.ongoingCustomProps}
                               currentPosition={3}
                               labels={labels}
                               stepCount = {5}
                          />
But the colors / styles are not reflecting/changing.

Please help me out here.

**Comment by timolins** [comment]
Duplicate of #31. I already submitted a [pull request](https://github.com/24ark/react-native-step-indicator/pull/32) to fix this behaviour.

**Comment by PriyankaAshu** [comment]
Hello Timolins,
Can I know when the dynamic styling will be update, Please ? 
I have already looked up for alternatives but react-native-step-indicator is only fits in my scope.

**Comment by 24ark** [comment]
I have published a new version(0.0.9) with support for dynamic styling.

**Comment by PriyankaAshu** [comment]
Thank you so much :)
