### ISSUE TITLE
support for custom label component

### ISSUE THREAD

**Issue by leejh3224** [24ark/react-native-step-indicator#48]
It would be nice if it adds support for custom label component instead of string

**Comment by sgtechmthinh** [comment]
any updates ?

**Comment by 24ark** [comment]
@leejh3224 @sgtechmthinh I am working on this feature and will release a new update of this library over the next weekend.

**Comment by sgtechmthinh** [comment]
> @leejh3224 @sgtechmthinh I am working on this feature and will release a new update of this library over the next weekend.

Nice! Looking forward from you

**Comment by 24ark** [comment]
@leejh3224 @sgtechmthinh I have released `v0.0.11` which includes functionality to render custom labels. I have updated the examples to showcase the functionality
