### ISSUE TITLE
The example project is not running

### ISSUE THREAD

**Issue by hamidhadi** [24ark/react-native-step-indicator#51]
After running the example project, I get this error
`Error: Couldn't find preset "es2015" relative to directory`

I also try to install babel preset es2015 but the problem isn't resolved.

**Comment by Richi2293** [comment]
Hi @hamidhadi , it's probably a little late. 
But I made a forked of the project and I managed to start the example:
https://github.com/Richi2293/react-native-step-indicator

This is in the readme:
https://github.com/Richi2293/react-native-step-indicator#how-to-run-example

**Comment by 24ark** [comment]
@hamidhadi I have updated the example project in version 0.0.10
