### ISSUE TITLE
Next and previous button 

### ISSUE THREAD

**Issue by rhenanteix** [24ark/react-native-step-indicator#54]
Good afternoon, I'm having trouble creating next and previous button, would you have any examples ??

I'm trying to use the RN navigation but it's not working, it brings me the error undefined is not object (evaluating this2.props.navigation.navigate)

**Comment by kmehmety** [comment]
Hello @rhenanteix. There is no content about changing pages in documentation. You may simply doing like this: 

> 

<Button title="Next" onPress={() => this.nextNextPage(this.state.currentPage + 1)} />
<Button title="Previous" onPress={() => this.nextNextPage(this.state.currentPage - 1)} />

nextNextPage(currentPage) {
    this.setState({ currentPage })
  }

>
