### ISSUE TITLE
Removing  swipe  between screens

### ISSUE THREAD

**Issue by SruthiSNair** [24ark/react-native-step-indicator#61]
Need validation in each swipe of screens. Please help me

**Comment by avanidhoot** [comment]
+1

**Comment by TheTaz25** [comment]
Hey there, this seems to be more an issue with the ViewPager instead of the step-indicator (if you are using the ViewPager).
I had a similar issue and fixed it by setting the attribute "horizontalScroll" to false in the ViewPager:
```        
          <ViewPager  
          ref={(pager) => this.pager = pager }  
          horizontalScroll={false}  
          >
```
I then validated all data inside of the View before I displayed a button at the bottom.
However you could build in a scrollblocker that blocks swiping until everything is validated:

```
state = {
  scrollblock: true,
  currentPage: 0
}

render(){
  <View>
    <StepIndicator
      currentPosition={this.state.currentPage}
      labels={["One", "Two", "Three"]}
      stepCount={3}
    />
    <ViewPager
      ref={(pager) => this.pager = pager}
      horizontalScroll={!this.state.scrollblock}
    >
    <View>
      <PageOne
        setScrollBlock={(val) => {
          this.setState({ scrollblock: val });
        }}
      />
    </View>
    <View>
      <PageTwo
        setScrollBlock={(val) => {
          this.setState({ scrollblock: val });
        }}
      />
    </View>
    <View>
      <PageThree
        setScrollBlock={(val) => {
          this.setState({ scrollblock: val });
        }}
      />
    </View>
    </ViewPager>
  </View>
}
```

Hope this will help you!

**Comment by avanidhoot** [comment]
How did u proceed to Pagetwo from PageOne can you help me with that too!

**Comment by SruthiSNair** [comment]
> Hey there, this seems to be more an issue with the ViewPager instead of the step-indicator (if you are using the ViewPager).
> I had a similar issue and fixed it by setting the attribute "horizontalScroll" to false in the ViewPager:
> 
> ```
>           <ViewPager  
>           ref={(pager) => this.pager = pager }  
>           horizontalScroll={false}  
>           >
> ```
> I then validated all data inside of the View before I displayed a button at the bottom.
> However you could build in a scrollblocker that blocks swiping until everything is validated:
> 
> ```
> state = {
>   scrollblock: true,
>   currentPage: 0
> }
> 
> render(){
>   <View>
>     <StepIndicator
>       currentPosition={this.state.currentPage}
>       labels={["One", "Two", "Three"]}
>       stepCount={3}
>     />
>     <ViewPager
>       ref={(pager) => this.pager = pager}
>       horizontalScroll={!this.state.scrollblock}
>     >
>     <View>
>       <PageOne
>         setScrollBlock={(val) => {
>           this.setState({ scrollblock: val });
>         }}
>       />
>     </View>
>     <View>
>       <PageTwo
>         setScrollBlock={(val) => {
>           this.setState({ scrollblock: val });
>         }}
>       />
>     </View>
>     <View>
>       <PageThree
>         setScrollBlock={(val) => {
>           this.setState({ scrollblock: val });
>         }}
>       />
>     </View>
>     </ViewPager>
>   </View>
> }
> ```
> Hope this will help you!

**Comment by SruthiSNair** [comment]
@TheTaz25  Is it possible to get  the scroll event ? then only i can validate accordingly  

or any other way for validation ?

**Comment by TheTaz25** [comment]
@avanidhoot I am currently a little bit short on time with work. It might take a few more days until I do have something shareable.

@SruthiSNair ViewPager offers 3 functions: onPageScroll, onPageScrollStateChanged, onPageSelected. One of the first two Callback-Functions will provide you with the needed scroll event. Add a testfunction and check which suits your needs. The ReactNative-ViewPager does not give any information on that.

**Comment by mariomurrent-softwaresolutions** [comment]
horizontalScroll={false} does not work for me :(
