### ISSUE TITLE
labelAlign property not being applied

### ISSUE THREAD

**Issue by gtiongco95** [24ark/react-native-step-indicator#66]
Hi there,

I have tried using the property "labelAlign" with either values 'right' or 'left' to align the labels to the either side. However, the labels' alignment does not update and is still has the default 'center' alignment.

**Comment by rdgomt** [comment]
Same here

**Comment by amanjuneja3012** [comment]
same here

**Comment by 24ark** [comment]
Can you try `flex-start` or `flex-end` and see if it works.

**Comment by ddsr17** [comment]
Still doesn't work

**Comment by gtiongco95** [comment]
The fix was in the line { alignItems: this.**state**.customStyles.labelAlign } where state was omitted. However, the values left and right only work for ios. If you want it to work with android as well you will need to use flex-start and flex-end.

**Comment by ddsr17** [comment]
@gtiongco95  Could you elaborate a bit, where exactly is this { alignItems: this.state.customStyles.labelAlign } to be placed?

**Comment by gtiongco95** [comment]
@ddsr17 it's located on line 287 of the StepIndicator.js file. It has been updated by the repo owner so it should just work now for you (:

**Comment by gtl-himanshu** [comment]
```
const customStyles = {
    labelAlign: 'flex-start', // <-- add this property to the custom styles object
};
```

>[ other type {"center" | "flex-start" | "flex-end" | "stretch" | "baseline" | undefined}](https://github.com/24ark/react-native-step-indicator/blob/master/src/types.ts)

**Comment by sagarpawarlive** [comment]
> Can you try `flex-start` or `flex-end` and see if it works.

This works thanks
