### ISSUE TITLE
Warning componentWillReceiveProps is being deprecated

### ISSUE THREAD

**Issue by MakhouT** [24ark/react-native-step-indicator#78]
As the title says, we are getting warnings that componentWillReceiveProps is deprecated and will be removed in the next major version.
Please update to get this warning removed.

I am on versions
react-native: 0.60.5
react: 16.8.6

**Comment by Relax594** [comment]
+1 with react-native: 0.61.1

**Comment by kpfefer** [comment]
#83 This is my personal attempt to fix it, not much testing done but I hope it helps

**Comment by 24ark** [comment]
Version 1.0.3 fixes this issue
