### ISSUE TITLE
in Android devices has problem

### ISSUE THREAD

**Issue by bestlbw** [24ark/react-native-step-indicator#8]
listview scrolling the StepIndicator was not follow

**Comment by 24ark** [comment]
@bestlbw The example uses `onChangeVisibleRows` prop of `ListView` to get visible rows on screen. At present `onChangeVisibleRows` is not supported on android. You can follow [this thread](https://github.com/facebook/react-native/pull/13532) for more informotion.

**Comment by 24ark** [comment]
@bestlbw I have updated the example to use FlatList instead of ListView. This should now work on android too.
