### ISSUE TITLE
Steps indicator dissapears

### ISSUE THREAD

**Issue by victormidp** [24ark/react-native-step-indicator#85]
After updating react native to the latest version some components started to hide in the Android version of my app, including this one. 
"react": "16.9.0",
"react-native": "0.61.1",
"react-native-step-indicator": "0.0.11"
I've been hunting this issue for weeks but without luck so far. There are no errors being thrown. Basically, the step indicator shows up fine the first time the screen is rendered, after that it loses visual elements.
My guess is that it could be related to the issue of "componentWillReceiveProps" warning being thrown.

<img src="https://user-images.githubusercontent.com/36865304/70855613-5a2ac680-1e93-11ea-8958-44b3d51909ef.png" data-canonical-src="https://user-images.githubusercontent.com/36865304/70855613-5a2ac680-1e93-11ea-8958-44b3d51909ef.png" width="200" height="400" />
<img src="https://user-images.githubusercontent.com/36865304/70855614-5f881100-1e93-11ea-934c-c73823df886c.png" data-canonical-src="https://user-images.githubusercontent.com/36865304/70855614-5f881100-1e93-11ea-934c-c73823df886c.png" width="200" height="400" />

**Comment by venkat77777** [comment]
I'm also facing the same issue,for me it's happening only on OnePlus devices. Only lines are disappearing on re-rendering, circles are rendering fine. Please check the below screenshot

![Screenshot_20200406-113357](https://user-images.githubusercontent.com/39147500/78527523-bd51b780-77fa-11ea-995d-8f17870a3ddb.jpg)
