### ISSUE TITLE
Custom renderStepIndicator is not centered on iOS

### ISSUE THREAD

**Issue by Relax594** [24ark/react-native-step-indicator#96]
Since we can't create issues in your fork, i'm doing it here @peterpme
A custom renderStepIndicator with a few custom styles lead to uncentered content inside the step indicator steps. But only on iOS, on Android it is fine.

```
<StepIndicator
        stepCount={stepCount}
        renderStepIndicator={renderStepIndicator}
        customStyles={indicatorStyle}
        currentPosition={currentPage}
        onPress={onStepPress}
        labels={labels}
 />

const indicatorStyle = {
        stepIndicatorSize: 20,
        currentStepIndicatorSize: 25,
        separatorStrokeWidth: 2,
        currentStepStrokeWidth: 3,
};

const renderStepIndicator = (params) => {
        return <MaterialCommunityIcon {...getStepIndicatorIconConfig(params)} />;
};

const getStepIndicatorIconConfig = ({ position, stepStatus }) => {
        const iconConfig = {
            name: icons[position],
            color: stepStatus === 'finished' ? '#ffffff' : activeIconColor,
            size: stepStatus === 'current' ? iconSize : iconSize - (activeStepSize - inactiveStepSize),
        };
        return iconConfig;
};
```
**Android:** perfectly centered
![grafik](https://user-images.githubusercontent.com/22765758/84772042-a8ec2100-afda-11ea-8f02-13e275e218d2.png)

**iOS:** not centered
![grafik](https://user-images.githubusercontent.com/22765758/84772532-5a8b5200-afdb-11ea-963e-50c556d69a8f.png)

**Comment by Relax594** [comment]
It is an issue with react-native-vector-icons on iOS: https://github.com/oblador/react-native-vector-icons/issues/1163

**Comment by Stophface** [comment]
@Relax594 DId you solve it? Same here...

**Comment by Relax594** [comment]
> @Relax594 DId you solve it? Same here...

as i've written it is an issue with react-native-vector-icons which is used in this lib. I just solved it by adding padding 1px left and top

**Comment by AyoubMoustahfid** [comment]
please share me your code, I need see some method create icons
